# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Audit
        run: npm audit
      - name: Build
        run: npm run build --if-present
      - name: Unit Test
        run: npm run test
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push auth service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.auth-service:latest
          file: apps/auth/Dockerfile
      - name: Build and push transactions service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.transactions-service:latest
          file: apps/transactions/Dockerfile
      - name: Build and push cashbacks service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.cashbacks-service:latest
          file: apps/cashbacks/Dockerfile
      - name: Build and push rewards service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.rewards-service:latest
          file: apps/rewards/Dockerfile
      - name: Build and push partners service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.partners-service:latest
          file: apps/partners/Dockerfile
      - name: Build and push wallets service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.wallets-service:latest
          file: apps/wallets/Dockerfile
      - name: Build and push notifications service
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arnurahman/kezbek-app.notifications-service:latest
          file: apps/notifications/Dockerfile
            
            
            
            
